"""Visual font preservation demo — compare pdf-edit-engine vs PyMuPDF.

Creates an invoice PDF with real TrueType fonts (Identity-H CIDFont),
edits it with both tools, and prints a side-by-side font comparison.

Usage::

    python scripts/demo_font_preservation.py

Output files are saved to demo_output/ for manual inspection.
"""

from __future__ import annotations

import sys
import traceback
from pathlib import Path

import pikepdf
from reportlab.lib.pagesizes import letter
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

from pdf_edit_engine import find, get_fonts, replace

DEMO_OUTPUT = Path(__file__).resolve().parent.parent / "demo_output"

ARIAL_PATH = Path("C:/Windows/Fonts/arial.ttf")
ARIAL_BOLD_PATH = Path("C:/Windows/Fonts/arialbd.ttf")
CALIBRI_PATH = Path("C:/Windows/Fonts/calibri.ttf")


def _find_ttf_font() -> tuple[str, Path, Path | None]:
    """Find a usable TrueType font on the system.

    Returns:
        Tuple of (font_family_name, regular_path, bold_path_or_None).
    """
    if ARIAL_PATH.exists():
        return "Arial", ARIAL_PATH, ARIAL_BOLD_PATH if ARIAL_BOLD_PATH.exists() else None
    if CALIBRI_PATH.exists():
        return "Calibri", CALIBRI_PATH, None
    return "", Path(), None


def _get_font_names(pdf_path: str) -> set[str]:
    """Extract all /BaseFont names from a PDF."""
    with pikepdf.Pdf.open(pdf_path) as pdf:
        fonts: set[str] = set()
        for page in pdf.pages:
            try:
                font_dict = page["/Resources"]["/Font"]
            except (KeyError, TypeError):
                continue
            for name in font_dict:
                try:
                    base = str(font_dict[name].get("/BaseFont", "unknown"))
                    fonts.add(base)
                except Exception:
                    continue
    return fonts


def create_original_pdf(output: Path, font_family: str, font_path: Path,
                        bold_path: Path | None) -> None:
    """Create an invoice PDF with registered TrueType fonts.

    Args:
        output: Path to save the PDF.
        font_family: Name to register the font as (e.g. "Arial").
        font_path: Path to the regular .ttf file.
        bold_path: Path to the bold .ttf file, or None.
    """
    pdfmetrics.registerFont(TTFont(font_family, str(font_path)))
    bold_name = font_family
    if bold_path and bold_path.exists():
        bold_name = f"{font_family}-Bold"
        pdfmetrics.registerFont(TTFont(bold_name, str(bold_path)))

    c = canvas.Canvas(str(output), pagesize=letter)

    # Title
    c.setFont(bold_name, 18)
    c.drawString(72, 730, "Invoice #2026-001")

    # Horizontal rule
    c.line(72, 720, 540, 720)

    # Body
    c.setFont(font_family, 12)
    c.drawString(72, 690, "Client: Acme Corporation")
    c.drawString(72, 670, "Amount: $15,000.00")
    c.drawString(72, 650, "Due Date: April 30, 2026")

    # Footer
    c.setFont(font_family, 9)
    c.drawString(72, 50, "Generated by pdf-edit-engine demo")

    c.save()


def edit_with_engine(input_pdf: Path, output: Path) -> bool:
    """Edit the invoice using pdf-edit-engine.

    Returns:
        True if both replacements succeeded.
    """
    src = str(input_pdf)
    success = True

    # First replacement: client name → intermediate file
    matches = find(src, "Acme Corporation")
    if not matches:
        print("  WARNING: engine could not find 'Acme Corporation'")
        return False

    intermediate = output.with_name("_intermediate.pdf")
    result = replace(src, matches[0], "GlobalTech Industries", str(intermediate), reflow=False)
    if not result.success:
        print(f"  WARNING: engine replace #1 failed: {result.warnings}")
        success = False

    # Second replacement: amount (intermediate → final output)
    matches2 = find(str(intermediate), "$15,000.00")
    if not matches2:
        print("  WARNING: engine could not find '$15,000.00'")
        intermediate.rename(output)
        return success

    result2 = replace(str(intermediate), matches2[0], "$22,500.00", str(output), reflow=False)
    if not result2.success:
        print(f"  WARNING: engine replace #2 failed: {result2.warnings}")
        success = False

    intermediate.unlink(missing_ok=True)
    return success


def edit_with_pymupdf(input_pdf: Path, output: Path) -> bool:
    """Edit the invoice using PyMuPDF (redact + re-insert).

    Returns:
        True if editing succeeded, False if PyMuPDF not available.
    """
    try:
        import fitz  # type: ignore[import-untyped]
    except ImportError:
        return False

    doc = fitz.open(str(input_pdf))
    page = doc[0]

    # Replace client name
    areas = page.search_for("Acme Corporation")
    for area in areas:
        page.add_redact_annot(area, text="GlobalTech Industries", fontsize=12)
    page.apply_redactions()

    # Replace amount
    areas2 = page.search_for("$15,000.00")
    for area in areas2:
        page.add_redact_annot(area, text="$22,500.00", fontsize=12)
    page.apply_redactions()

    doc.save(str(output))
    doc.close()
    return True


def print_summary(original: Path, engine_out: Path, pymupdf_out: Path | None) -> None:
    """Print the font comparison summary."""
    orig_fonts = _get_font_names(str(original))
    engine_fonts = _get_font_names(str(engine_out))

    # Also show encoding info from our engine
    engine_font_info = get_fonts(str(original))
    encoding_info = ", ".join(
        f"{fi.postscript_name} ({fi.encoding_type})" for fi in engine_font_info
    )

    print()
    print("=" * 56)
    print("  FONT PRESERVATION DEMO")
    print("=" * 56)
    print()
    print(f"  Original PDF: {original}")
    print(f"    Fonts: {sorted(orig_fonts)}")
    print(f"    Encoding: {encoding_info}")
    print()
    print(f"  Edited by pdf-edit-engine: {engine_out}")
    print(f"    Fonts: {sorted(engine_fonts)}")

    fonts_match = orig_fonts == engine_fonts
    print(f"    Match: {'SAME as original' if fonts_match else 'DIFFERENT!'}")

    if pymupdf_out and pymupdf_out.exists():
        pymupdf_fonts = _get_font_names(str(pymupdf_out))
        print()
        print(f"  Edited by PyMuPDF: {pymupdf_out}")
        print(f"    Fonts: {sorted(pymupdf_fonts)}")
        pymupdf_match = orig_fonts == pymupdf_fonts
        print(f"    Match: {'SAME as original' if pymupdf_match else 'DIFFERENT (font added)'}")

    # Verify text content
    from pdf_edit_engine import get_text

    engine_text = get_text(str(engine_out))
    has_client = "GlobalTech Industries" in engine_text
    has_amount = "$22,500.00" in engine_text
    print()
    print("  Text verification (engine):")
    print(f'    "GlobalTech Industries": {"found" if has_client else "MISSING"}')
    print(f'    "$22,500.00": {"found" if has_amount else "MISSING"}')

    print()
    print("=" * 56)
    print("  NOW OPEN THESE FILES:")
    print(f"    1. {original}")
    print(f"    2. {engine_out}")
    if pymupdf_out and pymupdf_out.exists():
        print(f"    3. {pymupdf_out}")
    print()
    print("  In Chrome or Adobe Reader, check:")
    print("    - Our edit: font looks IDENTICAL to original")
    if pymupdf_out and pymupdf_out.exists():
        print("    - PyMuPDF edit: replacement text looks DIFFERENT")
    print("=" * 56)
    print()


def main() -> None:
    """Run the font preservation demo."""
    # Find a system TTF font
    font_family, font_path, bold_path = _find_ttf_font()
    if not font_family:
        print("ERROR: No TrueType font found on this system.")
        print(f"  Checked: {ARIAL_PATH}, {CALIBRI_PATH}")
        sys.exit(1)

    print(f"Using font: {font_family} ({font_path})")

    # Create output directory
    DEMO_OUTPUT.mkdir(parents=True, exist_ok=True)

    original = DEMO_OUTPUT / "original.pdf"
    engine_out = DEMO_OUTPUT / "edited_by_engine.pdf"
    pymupdf_out = DEMO_OUTPUT / "edited_by_pymupdf.pdf"

    # Step 1: Create original PDF
    print("Creating original PDF...")
    create_original_pdf(original, font_family, font_path, bold_path)
    print(f"  Saved: {original}")

    # Step 2: Edit with our engine
    print("Editing with pdf-edit-engine...")
    try:
        edit_with_engine(original, engine_out)
        print(f"  Saved: {engine_out}")
    except Exception:
        print("  ERROR: Engine edit failed!")
        traceback.print_exc()
        sys.exit(1)

    # Step 3: Edit with PyMuPDF (optional)
    print("Editing with PyMuPDF...")
    pymupdf_path: Path | None = pymupdf_out
    if edit_with_pymupdf(original, pymupdf_out):
        print(f"  Saved: {pymupdf_out}")
    else:
        print("  (PyMuPDF not installed — skipping comparison)")
        pymupdf_path = None

    # Step 4: Print comparison
    print_summary(original, engine_out, pymupdf_path)


if __name__ == "__main__":
    main()
